import Head from "next/head";
import RegisterForm from "@/components/RegisterForm";

export default function Register() {
    let title = process.env.NEXT_PUBLIC_APP_TITLE || "Metin2 Next.JS App developed by TheoDoR";
    let pageTitle = `${title} - Register`;

    return (
        <>
            <Head>
                <title>{pageTitle}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <RegisterForm />
            </div>
        </>
    );
}
